import type { PipelineNodeDef } from "./graph";

export const GRAPH_VERSION_V3 = "revision@3";

export const PIPELINE_GRAPH_V3: PipelineNodeDef[] = [
  {
    id: "chi-muc-video",
    label: "Chỉ mục video",
    kind: "code",
    next: ["cong-an-toan"],
    userVisible: true,
  },
  {
    id: "cong-an-toan",
    label: "Cổng an toàn & PII",
    kind: "code",
    next: ["tach-y"],
    userVisible: true,
  },
  {
    id: "tach-y",
    label: "Tách ý & Intent",
    kind: "ai",
    next: ["dinh-vi"],
    userVisible: true,
  },
  {
    id: "dinh-vi",
    label: "Định vị lai & CRAG",
    kind: "code",
    next: ["kiem-chung"],
    userVisible: true,
  },
  {
    id: "kiem-chung",
    label: "Kiểm chứng nội dung",
    kind: "code",
    next: ["gom-van-de"],
    userVisible: false,
  },
  {
    id: "gom-van-de",
    label: "Gom vấn đề & Vùng bảo vệ",
    kind: "code",
    next: ["dinh-tuyen"],
    userVisible: true,
  },
  {
    id: "dinh-tuyen",
    label: "Định tuyến chuyên trách",
    kind: "code",
    next: ["bo-xu-ly"],
    userVisible: true,
  },
  {
    id: "bo-xu-ly",
    label: "Bộ xử lý chuyên trách",
    kind: "iteration",
    next: ["dong-co-thoi-gian"],
    userVisible: true,
  },
  {
    id: "xu-ly-am-thanh",
    label: "Đo âm thanh WCAG",
    kind: "code",
    childOf: "bo-xu-ly",
    next: [],
    userVisible: false,
  },
  {
    id: "xu-ly-phu-de",
    label: "Kiểm tra phụ đề",
    kind: "code",
    childOf: "bo-xu-ly",
    next: [],
    userVisible: false,
  },
  {
    id: "xu-ly-nhip",
    label: "Phân tích nhịp & khoảng dừng",
    kind: "code",
    childOf: "bo-xu-ly",
    next: [],
    userVisible: false,
  },
  {
    id: "xu-ly-hinh-anh",
    label: "Tín hiệu hình & slide",
    kind: "code",
    childOf: "bo-xu-ly",
    next: [],
    userVisible: false,
  },
  {
    id: "xu-ly-noi-dung",
    label: "Sửa lời sư phạm",
    kind: "ai",
    childOf: "bo-xu-ly",
    next: [],
    userVisible: false,
  },
  {
    id: "dong-co-thoi-gian",
    label: "Động cơ dòng thời gian & T1-T6",
    kind: "code",
    next: ["lap-ke-hoach"],
    userVisible: true,
  },
  {
    id: "lap-ke-hoach",
    label: "Quy hoạch ngân sách",
    kind: "code",
    next: ["tham-dinh"],
    userVisible: true,
  },
  {
    id: "tham-dinh",
    label: "Thẩm định giám khảo",
    kind: "code",
    next: ["tong-hop-brief"],
    userVisible: true,
  },
  {
    id: "tong-hop-brief",
    label: "Tổng hợp RevisionBrief",
    kind: "code",
    next: ["cho-duyet"],
    userVisible: true,
  },
  {
    id: "cho-duyet",
    label: "Chờ bạn duyệt",
    kind: "human",
    next: ["xuat-ban"],
    userVisible: true,
  },
  {
    id: "xuat-ban",
    label: "Xuất bản 5 vai trò",
    kind: "code",
    next: [],
    userVisible: false,
  },
];
